/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JoyconLib;

import org.junit.Test;
import static org.junit.Assert.*;

import org.gradle.internal.impldep.org.hamcrest.CoreMatchers;
import org.gradle.internal.impldep.org.junit.Assume;

public class LibraryTest {

    @Test public void testJoycons() {
        // Assume.assumeThat(System.getProperty("java.version"), CoreMatchers.startsWith("11"));
        // JoyconExample.run(); 
    }
    
}
